Repository Bikossor/codestain, pull requests merged in 2020-10, with the labels that each got.

#37 Closes #36
  src/Codestain.ts
  src/types/InputLanguage.ts
Labels: enhancement, hacktober

#40 Introduce AST, Nodes and NodeTypes
  src/Interfaces/AbstractSyntaxTree.ts
  src/Interfaces/Node.ts
  src/Interfaces/NodeType.ts
  src/parser.ts
  test/codestain.test.js
Labels: enhancement, hacktober

#44 Transformer improvements
  src/transformer.ts
Labels: enhancement, hacktober

#48 Add package-lock.json to the repository
  package-lock.json
Labels: bug, hacktober

#51 Language-specific parsers
  main.js
  src/Codestain.ts
  src/parser/JavaScript.ts
  src/parser/index.ts
  test/codestain.test.js
Labels: enhancement, hacktober

#52 The parser should identify the keywords
  src/enums/TokenType.ts
  src/parser/JavaScript.ts
  src/tokenizer.ts
  test/codestain.test.js
Labels: enhancement

#57 Apostrophe is missing in the tokenizer
  src/tokenizer.ts
Labels: bug

#58 Improve example string
  main.js
Labels: enhancement, hacktober

#61 Added support for BraceLeft.
  src/parser/JavaScript.ts
Labels: bug, hacktober

#63 Added support for TokenType.Colon.
  src/parser/JavaScript.ts
Labels: bug, hacktober

#64 Added support for TokenType.BraceRight.
  src/parser/JavaScript.ts
Labels: bug, hacktober

#65 LessThan-Token is missing
  src/enums/TokenType.ts
  src/parser/JavaScript.ts
  src/tokenizer.ts
Labels: bug

#67 Minus-Token is missing
  src/parser/JavaScript.ts
Labels: bug
